import { readFile, mkdir, writeFile } from "node:fs/promises";
const html = await readFile(
  new URL("../dist-mobile/index.html", import.meta.url),
  "utf8",
);
if (/<(?:script[^>]*\bsrc|link[^>]*\bhref)=/i.test(html))
  throw new Error("Mobile bundle must contain inline scripts and styles");
await mkdir(new URL("../mobile/generated/", import.meta.url), {
  recursive: true,
});
await writeFile(
  new URL("../mobile/generated/game-html.ts", import.meta.url),
  `// Generated by pnpm --filter ant-atelier build:mobile.\nexport const gameHtml = ${JSON.stringify(html)};\n`,
);
