import { adminClient, expect, test } from "./fixtures";
import { artifactAssistanceResponse } from "../../../src/features/chat-artifact/model/assistance";

// Two tabs share a real authenticated session. The proposal is generated by the
// actual provider and all revisions use the normal Supabase API; no interception.
test("REF-25/27 stale Artifact AI apply and manual save preserve both tabs' work without overwriting a newer revision", async ({ page }) => {
  test.setTimeout(180_000);
  await page.goto("/");
  await expect(page.getByRole("heading", { name: /외우지 말고/ })).toBeVisible();
  await expect(page.getByTestId("app-shell")).toHaveAttribute("data-shortcuts-ready", "true");
  await page.getByRole("button", { name: "새 채팅", exact: true }).click();
  await expect(page.getByRole("textbox", { name: "영어 메시지", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Artifact 열기", exact: true }).click();
  const workspace = page.getByRole("dialog", { name: "Artifact workspace", exact: true });
  const creation = page.waitForResponse(response => new URL(response.url()).pathname === "/api/artifacts" && response.request().method() === "POST");
  await workspace.getByRole("button", { name: "Text artifact 만들기", exact: true }).click();
  const created = await creation;
  expect(created.ok()).toBe(true);
  const artifactId = (await created.json()).item.id as string;
  const editor = workspace.getByLabel("Artifact 내용", { exact: true });
  const source = "I has a reservation for tomorrow.";
  await editor.fill(source);
  await expect(workspace.getByTestId("artifact-autosave-status")).toHaveText("모든 변경사항 저장됨");
  async function versions() {
    const result = await adminClient().from("artifact_versions").select("id,content_text,version_number")
      .eq("artifact_id", artifactId).order("version_number");
    expect(result.error).toBeNull(); return result.data!;
  }
  await expect.poll(async () => (await versions()).at(-1)?.content_text).toBe(source);
  const before = await versions();
  const tab = await page.context().newPage();
  try {
    await tab.goto(page.url());
    await expect(tab.getByRole("textbox", { name: "영어 메시지", exact: true })).toBeEnabled();
    await tab.getByRole("button", { name: "Artifact 열기", exact: true }).click();
    const otherWorkspace = tab.getByRole("dialog", { name: "Artifact workspace", exact: true });
    const otherEditor = otherWorkspace.getByLabel("Artifact 내용", { exact: true });
    await expect(otherEditor).toHaveValue(source);

    const generation = page.waitForResponse(response => new URL(response.url()).pathname === "/api/ai/artifact-assistance" && response.request().method() === "POST", { timeout: 60_000 });
    await workspace.getByRole("button", { name: "AI 문법 제안", exact: true }).click();
    const generated = await generation;
    expect(generated.ok(), await generated.text()).toBe(true);
    const proposal = artifactAssistanceResponse.parse(await generated.json());
    expect(proposal.source).toBe("provider");
    expect(proposal.versionId).toBe(before.at(-1)!.id);
    expect(proposal.sourceContent).toBe(source);
    const suggestion = workspace.getByTestId("artifact-ai-suggestion");
    await expect(suggestion).toHaveText(proposal.result.suggestion);
    await expect(editor).toHaveValue(source);
    expect(await versions()).toEqual(before);

    const newer = "The second tab confirmed a reservation for Friday.";
    await otherEditor.fill(newer);
    await expect(otherWorkspace.getByTestId("artifact-autosave-status")).toHaveText("모든 변경사항 저장됨");
    await expect.poll(async () => (await versions()).at(-1)?.content_text).toBe(newer);
    const committed = await versions();
    expect(committed).toHaveLength(before.length + 1);
    expect(committed.slice(0, -1)).toEqual(before);
    let staleVersionPosts = 0;
    page.on("request", request => {
      if (new URL(request.url()).pathname === `/api/artifacts/${artifactId}/versions` && request.method() === "POST") staleVersionPosts++;
    });
    const assistance = workspace.getByRole("region", { name: "Artifact AI 도움", exact: true });
    const apply = assistance.getByRole("button", { name: "AI 제안 적용", exact: true });
    await apply.click();
    await expect(assistance.getByRole("alert")).toContainText("다른 창에서 Artifact가 변경됐어요");
    await expect(editor).toHaveValue(source);
    await expect(suggestion).toHaveText(proposal.result.suggestion);
    expect(await versions()).toEqual(committed);
    expect(staleVersionPosts).toBe(0);

    const unsaved = "My separate unsaved edit must survive this conflict.";
    await editor.fill(unsaved);
    await expect(assistance.getByRole("status")).toContainText("내용이 변경되어 이 제안을 적용할 수 없어요");
    await expect(apply).toBeDisabled();
    const retry = workspace.getByRole("button", { name: "Artifact 저장 다시 시도", exact: true });
    await expect(retry).toBeVisible();
    await expect(workspace.getByRole("alert").filter({ hasText: "초안을 복사한 뒤" })).toBeVisible();
    await expect(editor).toHaveValue(unsaved);
    await expect(suggestion).toHaveText(proposal.result.suggestion);
    expect(await versions()).toEqual(committed);
    await retry.click();
    await expect(retry).toBeEnabled();
    await expect(workspace.getByRole("alert").filter({ hasText: "초안을 복사한 뒤" })).toBeVisible();
    await expect(editor).toHaveValue(unsaved);
    expect(staleVersionPosts).toBe(0);
    expect(await versions()).toEqual(committed);
    await otherWorkspace.getByRole("button", { name: "Artifact 닫기", exact: true }).click();
    await tab.reload();
    await tab.getByRole("button", { name: "Artifact 열기", exact: true }).click();
    await expect(otherEditor).toHaveValue(newer);
    await expect(editor).toHaveValue(unsaved);
    expect(await versions()).toEqual(committed);
  } finally {
    await tab.close();
  }
});
