import type { Character, LearningHistory, Mission } from "./contracts";

export const seedCharacters: Character[] = [
  {
    id: "mia-hotelier",
    name: "Mia",
    role: "친절한 호텔리어",
    tagline: "여행 영어의 첫 문장을 함께 열어요",
    description:
      "런던의 부티크 호텔에서 일하는 따뜻하고 침착한 호텔리어예요. 천천히 말하고, 실수해도 자연스럽게 다시 시도하도록 도와줘요.",
    personality: ["다정함", "인내심", "격려형"],
    personaGoal: "호텔에 도착한 여행객이 안심하도록 따뜻하게 맞이하기",
    learningGoal: "학습자가 호텔과 여행 상황에서 자신 있게 먼저 말하도록 돕기",
    speakingStyle: "짧고 또렷한 영국식 영어, 필요한 순간에만 한국어 힌트",
    accent: "British",
    level: "입문",
    topics: ["여행", "호텔", "스몰토크"],
    palette: ["#ff8c6b", "#ffc65c"],
    emoji: "👩🏻‍💼",
    visibility: "public",
    creator: "Lingo Studio",
    learnerCount: 12480,
    rating: 4.9,
    createdAt: "2026-08-18T09:00:00.000Z",
  },
  {
    id: "leo-barista",
    name: "Leo",
    role: "수다스러운 바리스타",
    tagline: "커피 한 잔처럼 가볍게 시작해요",
    description:
      "뉴욕 브루클린의 작은 카페 바리스타예요. 유쾌한 질문과 자연스러운 리액션으로 주문부터 일상 대화까지 이끌어줘요.",
    personality: ["유쾌함", "호기심", "리액션왕"],
    personaGoal: "동네 사람들의 하루를 커피와 유쾌한 대화로 깨우기",
    learningGoal: "카페 주문과 일상 스몰토크의 긴장을 낮추기",
    speakingStyle: "편안한 미국식 영어, 자주 쓰는 구동사 중심",
    accent: "American",
    level: "초급",
    topics: ["카페", "일상", "친구"],
    palette: ["#5965da", "#9f7aea"],
    emoji: "🧑🏽‍🍳",
    visibility: "public",
    creator: "Everyday English",
    learnerCount: 8920,
    rating: 4.8,
    createdAt: "2026-08-23T09:00:00.000Z",
  },
  {
    id: "noah-neighbor",
    name: "Noah",
    role: "새로 만난 이웃",
    tagline: "어색한 침묵도 좋은 대화가 될 수 있어요",
    description:
      "밴쿠버에 사는 다정한 이웃이에요. 날씨, 취미, 동네 이야기를 통해 처음 만난 사람과 대화를 이어가는 법을 연습해요.",
    personality: ["차분함", "배려심", "관찰형"],
    personaGoal: "새로 이사 온 이웃이 동네에 편안히 적응하도록 돕기",
    learningGoal: "낯선 사람과 3분 이상 자연스럽게 대화를 이어가기",
    speakingStyle: "중립적인 북미 영어, 문장 확장 질문을 자주 사용",
    accent: "Canadian",
    level: "초급",
    topics: ["이웃", "취미", "날씨"],
    palette: ["#2aa889", "#75d5ae"],
    emoji: "🧑🏻‍🌾",
    visibility: "public",
    creator: "Lingo Studio",
    learnerCount: 6310,
    rating: 4.7,
    createdAt: "2026-08-30T09:00:00.000Z",
  },
];

export const seedMissions: Mission[] = [
  {
    id: "hotel-check-in",
    title: "호텔 체크인하기",
    subtitle: "예약 확인부터 조식 시간 질문까지",
    description:
      "프런트 직원 Mia에게 예약자 이름을 말하고, 객실과 조식 정보를 확인해 보세요. 완벽한 문장보다 먼저 말을 꺼내는 것이 목표예요.",
    category: "여행",
    location: "London · Hotel Lobby",
    difficulty: "입문",
    durationMinutes: 7,
    objectives: [
      { id: "reservation", label: "예약자 이름 말하기", hint: "I have a reservation under..." },
      { id: "passport", label: "여권 건네기", hint: "Here is my passport." },
      { id: "breakfast", label: "조식 시간 묻기", hint: "What time is breakfast?" },
    ],
    keyPhrases: [
      { english: "I'd like to check in.", korean: "체크인하고 싶어요." },
      { english: "It's under Minji Kim.", korean: "민지 김으로 예약했어요." },
      { english: "Is breakfast included?", korean: "조식이 포함되어 있나요?" },
    ],
    rewardTitle: "Mia의 런던 야경",
    rewardPalette: ["#342a70", "#fa8c73"],
    rewardEmoji: "🌃",
    recommendedCharacterId: "mia-hotelier",
    learnerCount: 18730,
    createdAt: "2026-08-10T09:00:00.000Z",
  },
  {
    id: "coffee-order",
    title: "내 취향대로 커피 주문하기",
    subtitle: "사이즈, 우유, 포장 여부까지 자연스럽게",
    description:
      "바리스타 Leo에게 원하는 메뉴와 옵션을 정확히 전달하세요. 주문 뒤 가벼운 스몰토크에도 도전해요.",
    category: "일상",
    location: "New York · Neighborhood Cafe",
    difficulty: "초급",
    durationMinutes: 6,
    objectives: [
      { id: "order", label: "음료 주문하기", hint: "Can I get a..." },
      { id: "option", label: "우유 옵션 바꾸기", hint: "Could I have oat milk?" },
      { id: "takeout", label: "포장 요청하기", hint: "To go, please." },
    ],
    keyPhrases: [
      { english: "Can I get a small latte?", korean: "작은 라테 한 잔 주세요." },
      { english: "Could you make it decaf?", korean: "디카페인으로 해 주실래요?" },
      { english: "That's everything, thanks.", korean: "이게 전부예요, 고마워요." },
    ],
    rewardTitle: "Leo의 비밀 메뉴",
    rewardPalette: ["#8b5536", "#f6c888"],
    rewardEmoji: "☕",
    recommendedCharacterId: "leo-barista",
    learnerCount: 14120,
    createdAt: "2026-08-15T09:00:00.000Z",
  },
  {
    id: "meet-neighbor",
    title: "새 이웃과 인사하기",
    subtitle: "자기소개하고 대화를 한 번 더 이어가기",
    description:
      "엘리베이터에서 만난 Noah에게 인사하고 동네에 관해 물어보세요. 후속 질문을 한 번 더 하는 것이 핵심이에요.",
    category: "관계",
    location: "Vancouver · Apartment",
    difficulty: "초급",
    durationMinutes: 8,
    objectives: [
      { id: "introduce", label: "먼저 자기소개하기", hint: "Hi, I just moved in..." },
      { id: "place", label: "동네 장소 묻기", hint: "Is there a good... nearby?" },
      { id: "followup", label: "후속 질문하기", hint: "How about you?" },
    ],
    keyPhrases: [
      { english: "I live just down the hall.", korean: "복도 바로 저쪽에 살아요." },
      { english: "How long have you lived here?", korean: "여기 얼마나 오래 사셨어요?" },
      { english: "It was nice meeting you.", korean: "만나서 반가웠어요." },
    ],
    rewardTitle: "Noah의 주말 산책",
    rewardPalette: ["#1c6654", "#b0dfb4"],
    rewardEmoji: "🌿",
    recommendedCharacterId: "noah-neighbor",
    learnerCount: 7840,
    createdAt: "2026-08-21T09:00:00.000Z",
  },
  {
    id: "airport-luggage",
    title: "공항에서 수하물 찾기",
    subtitle: "분실 수하물 데스크에 상황 설명하기",
    description:
      "도착한 짐이 보이지 않을 때 직원에게 가방 특징과 항공편 정보를 차분히 설명해 보세요.",
    category: "여행",
    location: "Heathrow · Baggage Claim",
    difficulty: "중급",
    durationMinutes: 10,
    objectives: [
      { id: "problem", label: "문제 설명하기", hint: "My bag hasn't arrived." },
      { id: "describe", label: "가방 특징 말하기", hint: "It's a large blue suitcase." },
      { id: "next", label: "다음 절차 묻기", hint: "What should I do next?" },
    ],
    keyPhrases: [
      { english: "My luggage is missing.", korean: "제 짐이 없어졌어요." },
      { english: "Here is my baggage tag.", korean: "여기 수하물 표가 있어요." },
      { english: "Can it be delivered to my hotel?", korean: "호텔로 보내주실 수 있나요?" },
    ],
    rewardTitle: "여행 해결사 배지",
    rewardPalette: ["#285a84", "#74c4e8"],
    rewardEmoji: "🧳",
    recommendedCharacterId: "mia-hotelier",
    learnerCount: 5260,
    createdAt: "2026-08-28T09:00:00.000Z",
  },
];

export const initialHistories: LearningHistory[] = [
  {
    id: "history-hotel",
    characterId: "mia-hotelier",
    missionId: "hotel-check-in",
    title: "Mia와 호텔 체크인",
    preview: "I'd like to check in. The reservation is under Minji Kim.",
    lastActiveAt: "2026-09-05T08:40:00.000Z",
    turnCount: 8,
  },
  {
    id: "history-coffee",
    characterId: "leo-barista",
    missionId: "coffee-order",
    title: "Leo와 카페 주문",
    preview: "Could I have oat milk instead?",
    lastActiveAt: "2026-09-03T12:10:00.000Z",
    turnCount: 12,
  },
];
