

export const styles = {
  shell: {
    display: "grid",
    minHeight: "640px",
    gridTemplateColumns: "minmax(340px, 0.8fr) minmax(0, 1.2fr)",
    border: "1px solid #d8dee8",
    borderRadius: "8px",
    overflow: "hidden",
    background: "#f6f7f9",
  },
  side: {
    display: "grid",
    alignContent: "start",
    gap: "14px",
    borderRight: "1px solid #d8dee8",
    padding: "18px",
    background: "#ffffff",
  },
  chat: {
    minHeight: "640px",
  },
  title: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontWeight: 700,
    color: "#17202a",
  },
  panel: {
    display: "grid",
    gap: "12px",
    border: "1px solid #cbd7e3",
    borderRadius: "8px",
    padding: "14px",
    background: "#f9fbfd",
  },
  textarea: {
    minHeight: "120px",
    resize: "vertical" as const,
    border: "1px solid #cbd7e3",
    borderRadius: "8px",
    padding: "10px",
    font: "inherit",
    color: "#17202a",
  },
  row: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "8px",
  },
  button: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    border: "1px solid #cbd7e3",
    borderRadius: "8px",
    padding: "8px 10px",
    background: "#ffffff",
    color: "#17202a",
    cursor: "pointer",
    font: "inherit",
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    border: "1px solid #1f6feb",
    borderRadius: "8px",
    padding: "8px 10px",
    background: "#1f6feb",
    color: "#ffffff",
    cursor: "pointer",
    font: "inherit",
  },
  rejectedButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    border: "1px solid #d1242f",
    borderRadius: "8px",
    padding: "8px 10px",
    background: "#ffffff",
    color: "#b4232d",
    cursor: "pointer",
    font: "inherit",
  },
  empty: {
    border: "1px dashed #cbd7e3",
    borderRadius: "8px",
    padding: "14px",
    color: "#5f6b7a",
  },
};
