FROM langchain/langgraph-api:3.11

# -- Adding local package . --
ADD . /deps/3-langgraph-fast
# -- End of local package . --

# -- Installing all local dependencies --
RUN for dep in /deps/*; do \
        echo "Installing $dep"; \
        if [ -d "$dep" ]; then \
            (cd "$dep" && PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -e .); \
        fi; \
    done
# -- End of local dependencies install --

ENV LANGSERVE_GRAPHS='{"main_graph": "/deps/3-langgraph-fast/src/graph/main_graph/workflow.py:main_graph", "tenk_subgraph": "/deps/3-langgraph-fast/src/graph/subgraph/tenk/workflow.py:tenk_subgraph", "starter_graph": "/deps/3-langgraph-fast/src/graph/subgraph/starter_graph/workflow.py:starter_graph"}'

# -- Ensure user deps did not inadvertently overwrite langgraph-api --
RUN mkdir -p /api/langgraph_api /api/langgraph_runtime /api/langgraph_license \
    && touch /api/langgraph_api/__init__.py /api/langgraph_runtime/__init__.py /api/langgraph_license/__init__.py
RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir --no-deps -e /api
# -- End of ensuring user deps did not inadvertently overwrite langgraph-api --

RUN pip uninstall -y pip setuptools wheel
RUN rm -rf /usr/local/lib/python*/site-packages/pip* /usr/local/lib/python*/site-packages/setuptools* /usr/local/lib/python*/site-packages/wheel* \
    && find /usr/local/bin -name "pip*" -delete || true
RUN rm -rf /usr/lib/python*/site-packages/pip* /usr/lib/python*/site-packages/setuptools* /usr/lib/python*/site-packages/wheel* \
    && find /usr/bin -name "pip*" -delete || true
RUN uv pip uninstall --system pip setuptools wheel && rm /usr/bin/uv /usr/bin/uvx

WORKDIR /deps/3-langgraph-fast
